<?= Tag::js('jquery/jquery.min'); ?>




<!--  esto javascript es para ver si la orden que se esta creando ya existe   -->
<!--<script type='text/javascript'>
  function busca(){
    var exp = $('#exppenal').val();
    var ani = $('#anipenal').val();
    var juz = $('#juzgados_id').val();
    var tipo = $('#tiposoa_id').val();
    $.ajax({   
        type: "GET",
      url: "<?php //echo PUBLIC_PATH."ordenes/existe/" ?>"+exp+"/"+ani+"/"+juz+"/"+tipo,
      success: function(data){
      alert(data.responseText);
      }
    error: function(){ alert('error'); }
    });
    return false;
  }
</script>-->

 
<section class="content">
  <div class="box box-primary">
<h2 class="box-title">****Iniciar Orden****   </h2>
    <div class="box-body">

                 <div class="col-md-6">
                    <label ingreso>Expediente Penal :</label> </label><?php
                    echo form::text( 'type="number" class="form-control" required=""  id="exppenal" placeholder="Inserte expediente penal" onblur="convierte(this)" ')?> 
                </div>
                <div class="col-md-6">
                    <label class="text-blue text-center">Año Penal : </label>
                    <input type="number" class="form-control" required="" id="anipenal" placeholder="Inserte numero penal">
                </div>

                <div class="col-md-6">
                    <label class="ingreso">Juzgado : </label>
                    <?php echo Form::dbSelect('juzgados_id','juzgado',array('juzgados','listar'),'Seleccione','class="form-control select2" style="width: 100%" required=""') ?>
                </div>
                <div class="col-md-6">
                    <label class="ingreso">Tipo de Orden:</label>
                    <?php echo Form::dbSelect('tiposoa_id','descripcion',array('tiposoa','listar'),'Seleccione','class="form-control select2" style="width: 100%" required=""') ?>                   </div>
            




                
                <!-- -->
                <!--<div class="box-footer">
          <div class="col-md-12">
            <a href="<?php echo PUBLIC_PATH.'orden/crear/'.$idexpcifrado?>" class="btn btn-lg btn-warning btn-flat pull-right boton">Cancelar</a>

            <button class="btn btn-lg btn-primary btn-flat pull-right boton">Guardar</button>
          </div>
        </div>-->
          

<!-- --></div>
 <div class="row form-group" >
                    <div class="col-md-2 col-xs-12 col-sm-2 col-md-offset-5">
                    <button type="submit"  name="boton_buscar" id="boton_buscar" value="enviado" class="btn btn-success btn-flat">Buscar</button>
                </div>
                    <div class="col-md-2 col-xs-12 col-sm-2 col-lg-2">
                    <button class="btn btn-warning btn-flat" type="reset">Limpiar</button>
        </div>

      </div>

 


    </div>


</section>


  
