<?php header('Content-Type: text/html; charset=utf-8'); ?> 
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
 
 <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge">-->

  <title>EXPEDIENTES</title>
  <!-- Tell the browser to be responsive to screen width -->
 <!-- <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">-->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="Content-Type" content="text/javascript; charset=utf-8" />
<meta name="base_url" content="<?php echo PUBLIC_PATH ?>">

<!--Archivos css-->
<link href="<?php echo PUBLIC_PATH ?>css/bootstrap.min.css" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo PUBLIC_PATH ?>css/_all-skins.min.css" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo PUBLIC_PATH ?>css/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo PUBLIC_PATH ?>css/AdminLTE.min.css" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo PUBLIC_PATH ?>css/ionicons.min.css" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo PUBLIC_PATH ?>css/font-awesome.min.css" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo PUBLIC_PATH ?>css/custom.css" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo PUBLIC_PATH ?>css/plugins/jquery.datetimepicker.css" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo PUBLIC_PATH ?>css/plugins/easy-autocomplete.css" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo PUBLIC_PATH ?>css/plugins/bootstrap-select.min.css" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo PUBLIC_PATH ?>css/plugins/bootstrap-tagsinput.css" rel="stylesheet" type="text/css" media="screen">

<?php echo Tag::js('plugins/jquery-2.2.3.min'); ?>

<body class="hold-transition skin-blue sidebar-mini " >
<div class="wrapper" >

  <!-- Main Header -->
  <header class="main-header" >

    <!-- Logo -->
    <a href="<?php echo PUBLIC_PATH ?>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><i class="fa fa-home"></i></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><i class="fa fa-home"></i>INICIO</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
 
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
               <?php echo Html::img('logofondo.jpg','una imagen', array('class'=>'user-image'))?>
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs"><?php echo Session::get('nombre').' '.Session::get('paterno').' '.Session::get('materno')?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
              <?php echo Html::img('logofondo.jpg','una imagen', array('class'=>'img-circle'))?>
              <p><?php echo Session::get('nombre').' '.Session::get('paterno').' '.Session::get('materno')?></p>
              </li>
           
             
              <!-- Menu Footer-->
              <li class="user-footer">

                <div class="pull-right">
                  <a href="<?php echo PUBLIC_PATH ?>principal/salir" class="btn btn-default btn-flat" >Cerrar Sesión</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar"  >

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <?php echo  Html::img('logofondo.jpg','una imagen', array('class'=>'img-circle'))?>
        </div>
        <div class="pull-left info">
          <p><?php echo Session::get('titulo').' '.Session::get('nombre') ?></p>
          <!-- Status -->
         
        </div>
      </div>

      <!-- search form (Optional) 
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      /.search form -->
      <?php if(isset($expediente)): ?>
      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header"></li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="<?php echo PUBLIC_PATH ?>expedientes/editarExpediente/<?php echo $idexpcifrado?>"><i class="fa fa-folder text-primary"></i> <span>DATOS DEL EXPEDIENTE </span></a></li>
        <li><a href="<?php echo PUBLIC_PATH ?>expedientes/estatusexpediente/<?php echo $idexpcifrado?>"><i class="fa fa-book" style="color: #43ccb9!important"></i> <span>STATUS DEL EXPEDIENTE </span></a></li>
        <?php if ($expediente->sadais_id==8): ?>
          <li><a href="<?php echo PUBLIC_PATH ?>narcoticos/formedit/<?php echo $idexpcifrado?>"><i class="fa  fa-flask text-aqua"></i> <span>NARCOTICOS </span></a></li>
        <?php endif ?>
        <li><a href="<?php echo PUBLIC_PATH ?>denunciantes/formedit/<?php echo $idexpcifrado?>"><i class="fa fa-user text-gray"></i> <span>DENUNCIANTES </span></a></li>
        <li><a href="<?php echo PUBLIC_PATH ?>testigos/formedit/<?php echo $idexpcifrado?>"><i class="fa fa-user text-yellow"></i> <span>TESTIGOS </span></a></li>
        <li><a href="<?php echo PUBLIC_PATH ?>ofendidos/formedit/<?php echo $idexpcifrado?>"><i class="fa fa-user text-green"></i> <span>VICTIMAS </span></a></li>
        <li><a href="<?php echo PUBLIC_PATH ?>indiciados/formedit/<?php echo $idexpcifrado?>"><i class="fa fa-user-secret text-red"></i> <span>IMPUTADOS </span></a></li>
        <li><a href="<?php echo PUBLIC_PATH ?>vehiculos/formedit/<?php echo $idexpcifrado?>"><i class="fa fa-car text-teal"></i> <span>VEHICULOS </span></a></li>
        <li><a href="<?php echo PUBLIC_PATH ?>bienesasegurados/formedit/<?php echo $idexpcifrado?>"><i class="fa fa-archive text-maroon"></i> <span>BIENES ASEGURADOS </span></a></li>
        <?php if ($expediente->sadais_id==1): ?>
          <li><a href="<?php echo PUBLIC_PATH ?>involucrados/formedit/<?php echo $idexpcifrado?>"><i class="fa fa-user text-aqua"></i> <span>INVOLUCRADOS </span></a></li>
        <?php endif ?>
         <li><a href="<?php echo PUBLIC_PATH ?>expedientes/ubicacionExpediente/<?php echo $idexpcifrado?>"><i class="fa fa-map-marker text-orange"></i> <span>UBICACIÓN </span></a></li>
         
         <li><a href="<?php echo PUBLIC_PATH ?>ofeindis/formedit/<?php echo $idexpcifrado?>"><i class="fa fa-legal text-purple"></i> <span>DELITOS </span></a></li>
        
     


        <!--<li class="treeview">
          <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="#">Link in level 2</a></li>
            <li><a href="#">Link in level 2</a></li>
          </ul>
        </li>-->
      </ul>
    <?php endif ?>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>
<!--INICIO:Modal para los campos que necesitan ser llenados -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title text-red">No puede guardar el expediente, tiene campos sin completar</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="div_campos">
      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
<!--FIN:Modal para los campos que necesitan ser llenados -->


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    

    <!-- Main content -->
    <section class="content">

     <?php View::content() ?>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
    
  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
    
    </div>
    <!-- Default to the left -->
    <strong>Fiscalía general del estado de Oaxaca</strong> 
  </footer>
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->


<?php

echo Tag::js('plugins/bootstrap.min');
echo Tag::js('plugins/fastclick');
echo Tag::js('plugins/app.min');
echo Tag::js('plugins/jquery.sparkline.min');
echo Tag::js('plugins/jquery-jvectormap-1.2.2.min');
echo Tag::js('plugins/jquery-jvectormap-world-mill-en');
echo Tag::js('plugins/jquery.slimscroll.min');
echo Tag::js('plugins/Chart.min');
echo Tag::js('plugins/demo');
echo Tag::js('plugins/sweetalert2');
echo Tag::js('plugins/datetimepicker-master/jquery.datetimepicker.full.min');
echo Tag::js('plugins/EasyAutocomplete/jquery.easy-autocomplete.min');
echo Tag::js('plugins/validator');
echo Tag::js('plugins/bootstrap-select.min');
echo Tag::js('plugins/defaults-es_ES');
echo Tag::js('formularios/formularios'); 
echo Tag::js('plugins/bootstrap-tagsinput.min'); 

?>

<script type="text/javascript">
</script>
</body>
</html>
